Author.create(name: 'Snake')
Book.create(title: 'AAAA', author_id: 1)
Book.create(title: 'BBBBB', author_id: 1)
Book.create(title: 'CCC', author_id: 1)
Book.create(title: 'SSSSS', author_id: 1)
Book.create(title: 'LLLLL', author_id: 1)